### ISSUE TITLE
It is unclear if I need a DOM to use this project

### ISSUE THREAD

**Issue by 0xR** [pzavolinsky/react-unit#1]
Can I use this in mocha without any jsdom / phantomjs? The code seems to suggest shallow rendering is used internally, but the sizzle lib requires a dom.

**Comment by pzavolinsky** [comment]
HI @0xR, this library creates a minimal dom mock to allow sizzle to work. That coupled with recursive shallow rendering (ha, that sounded strange) allows you to do unit tests without jsdom or phantomjs.

In my examples I'm currently using gulp-jasmine to run the tests as a gulp task, but I presume using mocha should be more or less the same.

You can try the following to see a working example:

```shell
git clone git@github.com:pzavolinsky/react-unit.git
cd react-unit
npm install
gulp test
```
On an unrelated note, the dom mock is indeed /minimal/ and some complex sizzle selectors might not work. If you find any of these, create a separate issue (with the broken selector and a sample component) and I'll check them out (or, even better submit a pull request).

Cheers.

**Comment by 0xR** [comment]
Ok that's awesome news. You should put that on the top of your readme. I have not found any other library which allows you to do a find action without a dom. I'm looking forward to trying it out.

**Comment by pzavolinsky** [comment]
Cool, updated!

Make sure to check the tests in the [test/](https://github.com/pzavolinsky/react-unit/tree/master/test) directory for inspiration.
