### ISSUE TITLE
extra spaces contained in element.text as returned by queries

### ISSUE THREAD

**Issue by bdo** [pzavolinsky/react-unit#10]
When components are created, the property `text` is set to the concatenation of its texts.
It works in most cases. However it adds some extra spaces as the code joins texts together by adding spaces.

It makes tests difficult to write.

For instance, consider this simple react component that displays a time period:

```
const DateRange = ({from, to}) => {
  return <div>{from} - {to}</div>
}
```

When testing with the following code:
```
var component = createComponent(<DateRange from="Mon" to="Tue"/>);
expect(component.findByQuery('div')[0].text).to.equal('Mon - Tue');
```

The code fails with the following:
```
AssertionError: expected 'Mon  -  Tue' to equal 'Mon - Tue'
      + expected - actual

      -Mon  -  Tue
      +Mon - Tue
```

**Comment by bentidy** [comment]
I have the same problem...

**Comment by pzavolinsky** [comment]
Version `1.1.0` fixes this issue but might break existing tests.

Two alternative workarounds are:
- Replace `.text` with `.texts.join(' ')` as in:
```js
expect(component.texts.join(' ')).toEqual('1 2 3');
```
- Do an explicit assertion on a text array (preferred):
```js
expect(component.texts.join(' ')).toEqual(['1', '2', '3']);
```
