### ISSUE TITLE
Testing Stateless components / functions

### ISSUE THREAD

**Issue by russellholmes** [pzavolinsky/react-unit#26]

**Comment by jjmax75** [comment]
I'm currently trying to test a stateless component, did you overcome this issue? Could you provide any details, thanks

**Comment by pzavolinsky** [comment]
Hi @jjmax75 and @russellholmes.

This issue made me go back and check all the tests for a stateless example. Since I couldn't find any I just included some here: [test/stateless.jsx](https://github.com/pzavolinsky/react-unit/blob/master/test/stateless.jsx).

Cheers!
