### ISSUE TITLE
Changing global document breaks tests

### ISSUE THREAD

**Issue by PeteJodo** [pzavolinsky/react-unit#3]
[This line](https://github.com/pzavolinsky/react-unit/blob/master/dist/sizzle-bundle.js#L14) is breaking tests using jsdom. Looks to be changing global document. Commenting it out fixes the tests but unsure if it breaks anything within this module

**Comment by kamilio** [comment]
I had the same problem and created Pull Request to fix it https://github.com/pzavolinsky/react-unit/pull/4

**Comment by kamilio** [comment]
I've opened PR for the issue as well.

https://github.com/facebook/fbjs/pull/59

**Comment by pzavolinsky** [comment]
Hi guys, expect this to be merged and published by next Monday.

Cheers.

**Comment by pzavolinsky** [comment]
Merged into master and published as v1.0.6.

Thanks @kamilio !
