### ISSUE TITLE
Drop global document with React 0.14

### ISSUE THREAD

**Issue by kamilio** [pzavolinsky/react-unit#5]
Once the React 0.14 is released, we can completely remove the global `document` and don't pollute global scope at all.

From https://github.com/facebook/fbjs/pull/59

> We'll push out a new fbjs version from here soon and then update the React dependency. 0.14 should be going out soon and I'll make sure it includes this.

Issue just as a reminder.

**Comment by thom-nic** [comment]
Can anyone confirm that react-unit works w/ react v0.14?  I'm getting this error since I upgraded:

```
     TypeError: Cannot read property 'hasOwnProperty' of undefined
      at Object.checkAndWarnForMutatedProps (node_modules/react-unit/node_modules/react/lib/ReactElementValidator.js:335:25)
      at Object.ReactReconciler.mountComponent (node_modules/react-unit/node_modules/react/lib/ReactReconciler.js:40:29)
      at [object Object].ReactCompositeComponentMixin.mountComponent (node_modules/react-unit/node_modules/react/lib/ReactCompositeComponent.js:247:34)
      at [object Object].wrapper [as mountComponent] (node_modules/react-unit/node_modules/react/lib/ReactPerf.js:70:21)
      at [object Object].ReactShallowRenderer._render (node_modules/react-unit/node_modules/react/lib/ReactTestUtils.js:391:14)
      at [object Object].ReactShallowRenderer.render (node_modules/react-unit/node_modules/react/lib/ReactTestUtils.js:375:8)
      at node_modules/react-unit/dist/react-unit.js:193:12
      at node_modules/react-unit/node_modules/ramda/dist/ramda.js:290:35
      at node_modules/react-unit/node_modules/ramda/dist/ramda.js:46:27
      at node_modules/react-unit/dist/react-unit.js:202:19
      at node_modules/react-unit/node_modules/ramda/dist/ramda.js:290:35
      at node_modules/react-unit/node_modules/ramda/dist/ramda.js:54:27
      at node_modules/react-unit/dist/react-unit.js:211:10
      at node_modules/react-unit/node_modules/ramda/dist/ramda.js:290:35
      at node_modules/react-unit/node_modules/ramda/dist/ramda.js:46:27
      at Context.<anonymous> (test/components/shared/header.jsx:13:23)
```

It's thrown when my test calls `createComponent( <Header title={props.label} /> );`

**Comment by kamilio** [comment]
I haven't upgraded yet. So cannot confirm, but I will do it tomorrow.

**Comment by pzavolinsky** [comment]
Hi @thom-nic and @kamilio , I just pushed a new version (1.0.9) of `react-unit` that is almost there. In my tests I manually replaced `node_modules/react-unit/node_modules/react` with the `0.14` and got 97% of my tests working.

I was bitten by react's issue [4461](https://github.com/facebook/react/issues/4461) if the same happens to you consider using `createComponent.shallow` to avoid rendering the component that calls `setState` in `componentWillMount`.
 
As far as the `react-unit` code, we could move forward to 0.14. I still need to research a little bit how to keep dependency compat with 0.13 and 0.14 at the same time.

Any suggestions are more than welcome!

Cheers.

**Comment by ghengeveld** [comment]
I'm seeing the same issue described by @thom-nic above. Here's my dependencies:

```
"dependencies": {
  "react": "^0.14.0",
  "react-bootstrap": "^0.27.2"
},
"devDependencies": {
  "babel-core": "^5.8.25",
  "babel-eslint": "^4.1.3",
  "babel-runtime": "^5.8.25",
  "chai": "^3.4.0",
  "eslint": "^1.7.3",
  "eslint-config-airbnb": "^0.1.0",
  "eslint-plugin-react": "^3.6.3",
  "mocha": "^2.3.3",
  "react-addons-test-utils": "^0.14.0",
  "react-unit": "^1.0.9",
  "sinon": "^1.17.2"
}
```

I've tried running the test/create-component.jsx (by adding it to my own test directory), but it fails with the same stacktrace. I was also able to exclude react-bootstrap from being the culprit.

**Comment by pzavolinsky** [comment]
Hi @thom-nic and @ghengeveld thanks for the feedback!

I managed to reproduce the issue when using `react` 0.14 in the main project (as in @ghengeveld 's `package.json`) but with a local (and outdated) `react` dependency in `node_modules/react-unit/node_modules/react` (as in @thom-nic 's stack trace). 

This happened because, even though I upgraded `react-unit` to support 0.14, I did not update the `package.json` to reflect these changes.

Now `react-unit`'s package.json to support both `0.13` and `0.14` versions of `react` and this resolved the issue (as least for me).

Please grab the latest `react-unit` package (version `1.0.10`) and let me know if you still have this issue.

Cheers!

**Comment by ghengeveld** [comment]
Confirmed, it now works with React v0.14. Here's my test for reference:

```javascript
import React from 'react';
import createComponent from 'react-unit';
import Header from '../../src/Header';

describe('Header', () => {
  const component = createComponent(<Header/>);

  it('should render a navbar', () => {
    const navbars = component.findByQuery('.navbar');
    expect(navbars.length).to.equal(1);
  });

  it('should display the title', () => {
    expect(component.text).to.equal('Catalog');
  });
});
```

**Comment by pzavolinsky** [comment]
Awesome, thanks @ghengeveld !

**Comment by boblauer** [comment]
Is there any update on this?  I'm seeing an issue where a 3rd party lib is checking for `global.document` and if it's present, tries to execute some client-side-only code.  Because react-unit defines `global.document`, that code executes and an error is thrown.

**Comment by pzavolinsky** [comment]
Hi @boblauer , completely forgot about this. Thanks for the reminder.

Already removed the dependency and pushed `1.1.3`.

**Comment by boblauer** [comment]
Thanks!
